import React from 'react'

import possibilityImg from '../../assets/possibility.png';
import './possibility.css';

function Possibility() {
  return (
    <div className="gpt3__possibility section__padding" id="possibility">
      <div className="gpt3__possibility-image">
        <img src={possibilityImg} alt="gpt3 possibility" />
      </div>
      <div className="gpt3__possibility-content">
        <h4>Unlock Possibilities Today</h4>
        <h2 className="gradient__text">GPT-3 has untapped potential beyond your imagination.</h2>
        <p>The quality of the text generated by GPT-3 is so high that it can be difficult to determine whether or not it was written by a human, which has both benefits and risks. 
        Thirty-one OpenAI researchers and engineers presented the original May 28, 2020 paper introducing GPT-3. 
        In their paper, they warned of GPT-3's potential dangers and called for research to mitigate risk. David Chalmers, an Australian philosopher, 
        described GPT-3 as "one of the most interesting and important AI systems ever produced."</p>
        <button type="button" href="https://en.wikipedia.org/wiki/GPT-3" className="slide">Source</button>
      </div>
    </div>
  )
}

export default Possibility